apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-app
  namespace: monitoring

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
      - name: flask-app
        image: ccr.ccs.tencentyun.com/devops-automation-jt/flask-monitor:v1  # ÄãµÄ Flask ¾µÏñ
        ports:
        - containerPort: 8080
